package edu.tecnilogica.entity;
// Generated 27-jun-2017 11:57:11 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RegistroSec generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_SEC", schema = "HR")
@SequenceGenerator(name = "migen", sequenceName = "REGISTRO_SEC_SEQ", allocationSize = 1, initialValue = 0)
public class RegistroSec implements java.io.Serializable {

	private BigDecimal id;

	public RegistroSec() {
	}

	public RegistroSec(BigDecimal id) {
		this.id = id;
	}

	@Id
	@GeneratedValue (strategy= GenerationType.AUTO, generator = "migen")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
